services:
  - type: web
    name: restaurant-search
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 3000
      - key: MYSQLHOST
        value: localhost
      - key: MYSQLPORT
        value: 3306
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        generateValue: true
      - key: MYSQLDATABASE
        value: restaurant_search

